site_name: xsun2001's note collection 
theme:
    name: material
site_url: https://xsun.io/MyNotes
repo_url: https://github.com/xsun2001/MyNotes
site_author: "@xsun2001"
copyright: "© 2022 Chenxi Xu"

markdown_extensions:
    - pymdownx.extra
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
